@echo off
echo Sætter netværksprofil til Private (kræver admin)...
powershell -Command "Set-NetConnectionProfile -NetworkCategory Private" 2>nul
echo Starter Familieoverblik...
venv\Scripts\uvicorn main:app --host 0.0.0.0 --port 8000
